const db = require('./db');
const crypto = require('crypto');

async function ensureAdmin() {
    console.log("Checking Admin User...");
    const email = 'admin@urbani.com';
    const password = 'password_123';
    const hash = 'hashed_' + password;

    try {
        const res = await db.query('SELECT * FROM usuarios_sistema WHERE email = $1', [email]);

        if (res.rows.length === 0) {
            console.log("Admin user missing. Creating it now...");

            // Try insert with explicit UUID generated by crypto
            const userId = crypto.randomUUID();

            try {
                await db.query(`
                    INSERT INTO usuarios_sistema (id, email, password_hash, nombre, role)
                    VALUES ($1, $2, $3, $4, $5)
                `, [userId, email, hash, 'Admin Urbani', 'admin']);
                console.log("✅ Admin user created successfully.");
            } catch (err) {
                console.error("Insert with UUID failed, trying default...", err.message);
                // Fallback to letting DB generate UUID
                try {
                    await db.query(`
                        INSERT INTO usuarios_sistema (email, password_hash, nombre, role)
                        VALUES ($1, $2, $3, $4)
                    `, [email, hash, 'Admin Urbani', 'admin']);
                    console.log("✅ Admin user created successfully (DB Default ID).");
                } catch (err2) {
                    console.error("All inserts failed:", err2.message);
                }
            }
        } else {
            console.log("✅ Admin user exists.");
            // Update password to be sure
            await db.query('UPDATE usuarios_sistema SET password_hash = $1 WHERE email = $2', [hash, email]);
            console.log("✅ Password reset to default: " + password);
        }

        console.log("\n--- CREDENTIALS ---");
        console.log("Email: " + email);
        console.log("Password: " + password);
        console.log("-------------------");

    } catch (e) {
        console.error("Error ensuring admin:", e.message);
    }
}

ensureAdmin();
